version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/myapp
      - restore_cache:
          key: nativescript-sidedrawer-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: nativescript-sidedrawer-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: tns test android
